// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Answer: typeof import('./src/components/Answer.vue')['default']
    AnswerBoard: typeof import('./src/components/AnswerBoard.vue')['default']
    Board: typeof import('./src/components/Board.vue')['default']
    CloseModal: typeof import('./src/components/CloseModal.vue')['default']
    ColCount: typeof import('./src/components/ColCount.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowCount: typeof import('./src/components/RowCount.vue')['default']
    SettingModal: typeof import('./src/components/SettingModal.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
  }
}

export {}
